import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

interface IAwards {
  wins: Number;
  nominations: Number;
  text: String;
}
interface IMovie {
  plot: String;
  genres: [String];
  runtime: Number;
  cast: [String];
  num_mflix_comments: Number;
  poster: String;
  title: String;
  fullplot: String;
  countries: [String];
  language: [String];
  released: Date;
  directors: [String];
  rated: String;
  awards: { wins: Number; nominations: Number; text: String };
  lastupdated: String;
  year: Date;
  imbd: { rating: Number; votes: Number; id: Number };
  type: String;
  tomatoes: {
    viewer: { rating: Number; numReviews: Number; meter: Number };
    fresh: Number;
    lastUpdated: Date;
    critic: { rating: Number; numReviews: Number; meter: Number };
    rotten: Number;
  };
}
interface IMovies {
  movies:IMovie[]
}

export default function Home(movies:[IMovies]) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-red-600">
        <h1>Welcome .</h1>
        <div>
          <div>
            <h1>Movies List</h1>
            <div>
              {movies.length > 0 &&
              movies.map((movie: IMovie) => (
                <div className="group" key={movie._id}>
                  <div className="aspect-[9/12] relative group bg-lime-200">
                    <Image
                      src={movie.poster || ""}
                      width={100}
                      height={100}
                      alt="moviePoster"
                      className="w-full h-full object-cover rounded"
                    />
                    <div className="absolute inset-0 group-hover:bg-black/30 transition-all" />
                  </div>
                  <Link
                    className="text-orange-400"
                    href={`movies/${movie._id}`}
                  >
                    {movie.title}
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}












export async function getServerSideProps({
  const res  = await fetch("http://localhost:8008/movies")
  const data = await res.json()
}
return{
  props:{movies : data.movies}
})